// Package licenses provides embedded license information
package licenses

import _ "embed"

// ThirdParty contains third-party dependency license information.
// In release builds this is generated by go-licenses; in development
// builds it contains a placeholder message.
//
//go:embed third-party.txt
var ThirdParty string
