on:
  release:
    types: [created]

name: Build & release
jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: "386"
            goos: windows
          - goarch: arm
            goos: darwin
          - goarch: arm
            goos: windows
    steps:
    - uses: actions/checkout@v3

    # build the assets
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - run: echo "Building assets for ${{ github.ref_name }}"
    - run: npm install
    - run: npm run package

    # build the binaries
    - uses: wangyoucao577/go-release-action@v1.38
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        binary_name: "mailpit"
        pre_command: export CGO_ENABLED=0
        asset_name: mailpit-${{ matrix.goos }}-${{ matrix.goarch }}
        extra_files: LICENSE README.md
        md5sum: false
        overwrite: true
        ldflags: -w -X "github.com/axllent/mailpit/config.Version=${{ github.ref_name }}"
